version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    groups:
      dev:
        dependency-type: "development"
        exclude-patterns:
          # We want to maintain control over which type updates we merge to make
          # sure they are in sync with the respective package
          - "@types/*"
      i18n:
        patterns:
          - "@formatjs/*"
          - "react-intl"
      blueprint:
        patterns:
          - "@blueprintjs/*"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: docker
    directory: "/ui"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
