"""make collections taggable

Revision ID: 48e003f89633
Revises: 5d52e680a2f3
Create Date: 2025-09-23 14:21:12.832825

"""

# revision identifiers, used by Alembic.
revision = "48e003f89633"
down_revision = "5d52e680a2f3"

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("taggable", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "taggable")
    # ### end Alembic commands ###
