"""create tag table

Revision ID: 5d52e680a2f3
Revises: e003034f4af8
Create Date: 2025-09-23 09:17:14.264825

"""

# revision identifiers, used by Alembic.
revision = "5d52e680a2f3"
down_revision = "e003034f4af8"

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("tag", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tag_entity_id"), "tag", ["entity_id"], unique=False)
    op.create_index(op.f("ix_tag_tag"), "tag", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tag_tag"), table_name="tag")
    op.drop_index(op.f("ix_tag_entity_id"), table_name="tag")
    op.drop_table("tag")
    # ### end Alembic commands ###
